### ISSUE TITLE
Find five papers to study

### ISSUE THREAD

**Issue by JRasmusBm** [JRasmusBm/2019_Pervasive_RoadRage#1]
1. [Immersion factors affecting perception and behaviour in a virtual reality power wheelchair simulator](https://www.sciencedirect.com/science/article/pii/S0003687016300904)
2. [Detecting Stress During Real-World Driving Tasks Using Physiological Sensors](http://www.hpl.hp.com/techreports/2004/HPL-2004-229.pdf)
3. [EEG Alpha asymmetry, heart rate variability and cortisol in response to Virtual Reality induced stress](https://www.researchgate.net/profile/Leslie_Van_Der_Leer/publication/239522474_EEG_alpha_asymmetry_heart_rate_variability_and_cortisol_in_response_to_Virtual_Reality_induced_stress/links/55ab680f08ae815a04279fa7/EEG-alpha-asymmetry-heart-rate-variability-and-cortisol-in-response-to-Virtual-Reality-induced-stress.pdf)
4. [A Critical Review of Proactive Detection of Driver Stress Levels Based on Multimodal Measurements](https://www.researchgate.net/publication/327477922_A_Critical_Review_of_Proactive_Detection_of_Driver_Stress_Levels_Based_on_Multimodal_Measurements)
5. [Inducing Anxiety through Video Material ](http://stress.few.vu.nl/publications/2014-BosseEtAl-HCII.pdf)

**Comment by Augiro** [comment]
[Risk of Motor Vehicle Accidents Related to Sleepiness at the Wheel: A Systematic Review and Meta-Analysis](https://academic.oup.com/sleep/article/40/10/zsx134/4049536)
[The Perceptual Quality of the Oculus Rift for Immersive Virtual Reality](https://www.tandfonline.com/doi/abs/10.1080/07370024.2016.1243478?journalCode=hhci20)
[Immersion factors affecting perception and behaviour in a virtual reality power wheelchair simulator
Author links open overlay panel](https://www.sciencedirect.com/science/article/pii/S0003687016300904)
[Motor Vehicle Crash Risk Among Adolescents and Young Adults With Attention-Deficit/Hyperactivity Disorder](https://jamanetwork.com/journals/jamapediatrics/fullarticle/2631767)
[The effect of zonal factors in estimating crash risks by transportation modes: Motor vehicle, bicycle and pedestrian](https://www.sciencedirect.com/science/article/abs/pii/S0001457516303797)
[Alcohol Policies and Alcohol-Related Motor Vehicle Crash Fatalities Among Young People in the US](http://pediatrics.aappublications.org/content/139/3/e20163037.abstract)

EDIT (@JRasmusBm): Took the freedom to change the links so they show the names of the papers, makes them easier to reason about.

**Comment by JRasmusBm** [comment]
Great job in finding so many papers already! Here are my thoughts:

> [Risk of Motor Vehicle Accidents Related to Sleepiness at the Wheel: A Systematic Review and Meta-Analysis](https://academic.oup.com/sleep/article/40/10/zsx134/4049536)

Interesting, but is it not slightly irrelevant? It discusses low levels of exitement, not high ones. It might still be useful to include a similar paper to figure out what measurements were used to determine the sleepiness of the test subjects, but in this one the level of sleepiness seems to have been based on self evaluation. Wouldn't it be better if we could find one where a body measurement was used?

> [The Perceptual Quality of the Oculus Rift for Immersive Virtual Reality](https://www.tandfonline.com/doi/abs/10.1080/07370024.2016.1243478?journalCode=hhci20)

I feel like this one would be useful for selecting which VR equipment to use, and not how to use it. I might accept the recommendation from the abstract, but is it necessary to read a whole paper for that?

> [Immersion factors affecting perception and behaviour in a virtual reality power wheelchair simulator](https://www.sciencedirect.com/science/article/pii/S0003687016300904)

:tada: This could be useful for designing an immersive experience for the user. Very nice find!

> [Motor Vehicle Crash Risk Among Adolescents and Young Adults With Attention-Deficit/Hyperactivity Disorder](https://jamanetwork.com/journals/jamapediatrics/fullarticle/2631767)

 :+1: Maybe we could use this to make a case that it is at least plausible that hyperactivity can negatively influence driving.

> [The effect of zonal factors in estimating crash risks by transportation modes: Motor vehicle, bicycle and pedestrian](https://www.sciencedirect.com/science/article/abs/pii/S0001457516303797)

 :angel: :question:I have to say that I don't understand completely what it is about. Might be interesting.

> [Alcohol Policies and Alcohol-Related Motor Vehicle Crash Fatalities Among Young People in the US](http://pediatrics.aappublications.org/content/139/3/e20163037.abstract)

I feel like this one is in the same spirit as [Motor Vehicle Crash Risk Among Adolescents and Young Adults With Attention-Deficit/Hyperactivity Disorder](https://jamanetwork.com/journals/jamapediatrics/fullarticle/2631767), and I prefer that one over this one.

**Comment by JRasmusBm** [comment]
What do you guys think about this one?

[A Critical Review of Proactive Detection of Driver Stress Levels Based on Multimodal Measurements](https://www.researchgate.net/publication/327477922_A_Critical_Review_of_Proactive_Detection_of_Driver_Stress_Levels_Based_on_Multimodal_Measurements)

**Comment by pluesia** [comment]
I found this paper, quite practical. It discuss about methods for collecting stress level while real driving with specific sensors.

[Detecting Stress During Real-World Driving Tasks Using Physiological Sensors](http://www.hpl.hp.com/techreports/2004/HPL-2004-229.pdf)

**Comment by LHJ** [comment]
This paper is the result of attempting to induce stress in virtual reality, admittadly through explosions and harsh critisism. Possibly interesting as making a case for being able to induce measurable stress at all in vr.  

[EEG Alpha asymmetry, heart rate variability and cortisol in response to Virtual Reality induced stress](https://www.researchgate.net/profile/Leslie_Van_Der_Leer/publication/239522474_EEG_alpha_asymmetry_heart_rate_variability_and_cortisol_in_response_to_Virtual_Reality_induced_stress/links/55ab680f08ae815a04279fa7/EEG-alpha-asymmetry-heart-rate-variability-and-cortisol-in-response-to-Virtual-Reality-induced-stress.pdf)

**Comment by JRasmusBm** [comment]
[Inducing Anxiety through Video Material ](http://stress.few.vu.nl/publications/2014-BosseEtAl-HCII.pdf)
