### ISSUE TITLE
Paper Two: Detecting Stress During Real-World Driving Tasks Using Physiological Sensors

### ISSUE THREAD

**Issue by JRasmusBm** [JRasmusBm/2019_Pervasive_RoadRage#7]
2. [Detecting Stress During Real-World Driving Tasks Using Physiological Sensors](http://www.hpl.hp.com/techreports/2004/HPL-2004-229.pdf)

**Comment by JRasmusBm** [comment]
> During high stress situations cell phone calls could be diverted to voice mail
and navigation systems be programmed to present the driver with only the most
critical information to help reduce driver workload. In addition, the music
selection agent might lower the volume, or offer a greater selection of
relaxing tunes to help the driver cope with their feelings of stress.
[ ... ]
Although none of the physiological signals monitored here react quickly enough
to contribute to automatic vehicle control, this kind of monitoring, with a one
to three minute lag in driver assessment, is fast enough to initiate customized
changes to the driver's in-vehicle environment to migitate emotional stress.

Hmm... if they are right, we will have to account for this.

It seems like automatic driving controls as response to emotions is not reliable, because it can have a lag of 1-3 minutes. They do however suggest that you could do other things in the car (change music, divert phone calls etc.). We could do that. We could also add a high end rule, so that if a driver is over a certain stress level, they are not allowed to drive.

What are your thoughts?

**Comment by JRasmusBm** [comment]
Maybe one could also use that information to signal the increased stress levels to other drivers, so that they can adapt to that information.

**Comment by JRasmusBm** [comment]
They measured skin conductivity in palms and feet, I wonder if that's ideal. Where does our equipment measure?

**Comment by TanguyFournier** [comment]
> For example, the skin conductivity latency is on the order of 1.4 seconds [37] andanticipatory EMG has been measured in the laboratory at 30 milliseconds [38].

What about the 1~3 min lag though ?

> Despite these limitations, these experiments show that physiological signals provide a viable method of measuring a driver’s stress level.

So it seems to be doable! 

> The results of the second analysis suggest that the first sensors that should be integrated into a car, or a mobile wearable device that communicates with a car, should be skin conductance and heart rate sensors.

Looks like heart rate isn't that useless according to this paper's authors...

Also, they had 2 different approaches : the first idea is to observe sensors results for 5min intervals and then determine a general stress level over thoses 5 mins (and they say that could be applicable to real-time applications, monitoring the last 5min continously) and the other is simply measuring stress level based on a real-time (1 sec intervals) observation of the sensors' results. So we'll have to make a choice about our own method.
I would suggest the real-time one as using the 5min observation will require us to build a machine learning algorithm to take the decision on the dirver's stess state (although it looks like to be less effective).

**Comment by JRasmusBm** [comment]
> What about the 1~3 min lag though ?

That is indeed very strange. Almost makes you wonder if there was an erroneous unit of measurement somewhere. We can try it out a bit ourselves later on, right?
 
> So it seems to be doable!

Yes, doable to measure the stress levels, but they also state clearly that they don't think it's applicable to critical systems (like the actual control of the vehicle).
 
> Looks like heart rate isn't that useless according to this paper's authors...

No, heart rate and skin conductance are the best measurements, that seems to be a consensus, but I think skin conductance seems the absolute best.

> Also, they had 2 different approaches : the first idea is to observe sensors results for 5min intervals and then determine a general stress level over thoses 5 mins (and they say that could be applicable to real-time applications, monitoring the last 5min continously) and the other is simply measuring stress level based on a real-time (1 sec intervals) observation of the sensors' results. So we'll have to make a choice about our own method.
> I would suggest the real-time one as using the 5min observation will require us to build a machine learning algorithm to take the decision on the dirver's stess state (although it looks like to be less effective).

When they did the 1 sec intervals, that didn't get passed to the car in real time at all, the way I understand it. Instead, that was monitored and used as a control metric after the fact. They actually had people look at the video and count signs of stress. I do think you're right, that we should try a real-time method. I hope we can make something work!
