### ISSUE TITLE
Paper Three: EEG Alpha asymmetry, heart rate variability and cortisol in response to Virtual Reality induced stress

### ISSUE THREAD

**Issue by JRasmusBm** [JRasmusBm/2019_Pervasive_RoadRage#8]
3. [EEG Alpha asymmetry, heart rate variability and cortisol in response to Virtual Reality induced stress](https://www.researchgate.net/profile/Leslie_Van_Der_Leer/publication/239522474_EEG_alpha_asymmetry_heart_rate_variability_and_cortisol_in_response_to_Virtual_Reality_induced_stress/links/55ab680f08ae815a04279fa7/EEG-alpha-asymmetry-heart-rate-variability-and-cortisol-in-response-to-Virtual-Reality-induced-stress.pdf)

**Comment by TanguyFournier** [comment]
>  We here found that alpha asymmetry correlated with associative stress when the eyes were closed, but
not when they were open. For heart variability, it was the other way around.

Opened eyes are kinda mandatory in our case so definitely not EEG. Maybe heart rate variability...
> Heart variability, especially as determined by the power in the high frequency range of the RRI, requires quite long windows of analysis.

But again, it looks like heart rate variability induces too much lag to lead to an automatic driving control response.
> In future experiments we plan to record skin conductance as well

Seems like they feel like they have missed something. Skin conductance sounds to be our best bet in the end...

**Comment by JRasmusBm** [comment]
> Seems like they feel like they have missed something. Skin conductance sounds to be our best bet in the end...

I think you're exactly right. If I had not read these papers I would have believed heart variability to be the best real-time indicators of stress. It's good we read up on this.

I also think it's very encouraging that they were able to elicit stress in a VR environment. That shows that it is at least possible, even if we may have to go to quite some measures to actually make it happen.
